### ISSUE TITLE
User Persona - {TITLE}

### ISSUE THREAD

**Issue by aditiagrwl** [batuaWallet/ux#3]
![THIS IS A SAMPLE IMAGE](https://user-images.githubusercontent.com/2212651/95482432-bc693080-09ab-11eb-9c64-f17d2542d8fa.png)

**Name:** _{Siddartha}_

**Gender:** _{gender}_

**Occupation:** _{occupation}_

**Marital Status:** _{marital status}_

**Location:** _{location}_

**Other traits:** _{other traits}_

**Why they need Batua:** _{why Batua}_

**How will they interact with Batua:** _{how Batua}_

**Obstacles they might face / questions they might ask:** _{barriers to entry}_

**Comment by chrishobcroft** [comment]
Closing this as it appears to be just the template without any content
